const {test,expect}=require('@playwright/test');
const root='http://127.0.0.1:8765/app/';
const initial=()=>({version:1,events:[],watchlist:[],journal:[],alerts:[],preferences:{allowMargin:false,costMethod:'average'}});
const profile={display_name:'Tester',locale:'nl-NL',timezone:'Europe/Amsterdam',display_currency:'EUR',risk_budget_eur:'100.00',version:1};
async function setup(page){let state=initial();let status=200;await page.route('http://127.0.0.1:8765/api/v1/**',async route=>{const r=route.request(),path=new URL(r.url()).pathname;if(status===401)return route.fulfill({status:401,json:{error:{code:'UNAUTHENTICATED'}}});if(path.endsWith('/session'))return route.fulfill({json:{data:{authenticated:true,settings:profile}}});if(path.endsWith('/settings'))return route.fulfill({json:{data:profile}});if(path.endsWith('/state')){if(r.method()==='PUT'){expect(r.headers()['x-tradepilot-csrf']).toBe('1');expect(r.postDataJSON().version).toBe(state.version);state={...r.postDataJSON(),version:state.version+1};}return route.fulfill({json:{data:state}});}return route.fulfill({status:503,json:{error:{code:'MARKET_NOT_CONFIGURED'}}});});return {get:()=>state,expire:()=>status=401};}
async function ready(page,url=root){await page.goto(url);await expect(page.locator('.splash')).toBeHidden();}
async function book(page,data){const f=page.locator('#ledger-form');await f.locator('[name=type]').selectOption(data.type);for(const [k,v] of Object.entries(data).filter(([k])=>k!=='type')){const input=f.locator('[name='+k+']');if(['currency','feeCurrency','toCurrency'].includes(k))await input.selectOption(v);else await input.fill(v);}await f.getByRole('button',{name:'Boeking opslaan'}).click();await expect(page.locator('#feature-message')).toContainText('Boeking opgeslagen');}
test('cash deposit, partial sale, re-entry and reload persist exact ledger',async({page})=>{const store=await setup(page);await ready(page,root+'portfolio');await expect(page.locator('#data-status')).toContainText('versie 1');await book(page,{type:'DEPOSIT',timestamp:'2026-10-01T10:00:00Z',amount:'1000'});await book(page,{type:'BUY',timestamp:'2026-10-02T10:00:00Z',symbol:'OPEN',quantity:'100',price:'3',fee:'1'});await book(page,{type:'SELL',timestamp:'2026-10-03T10:00:00Z',symbol:'OPEN',quantity:'40',price:'3.5',fee:'1'});await expect(page.locator('.dashboard-kpis .card').nth(0)).toContainText('838');await expect(page.locator('.dashboard-kpis .card').nth(2)).toContainText('18.6');expect(store.get().events).toHaveLength(3);await page.reload();await expect(page.locator('#data-status')).toContainText('versie 4');await expect(page.getByRole('heading',{name:'Posities',exact:true}).locator('..').getByRole('cell',{name:'OPEN',exact:true})).toHaveCount(1);});
test('CSV import previews and duplicate ids do not duplicate cash',async({page})=>{const store=await setup(page);await ready(page,root+'portfolio');await expect(page.locator('#data-status')).toContainText('versie 1');const {exportLedgerCSV}=await import('../app/ledger.mjs');await expect(page.locator('#ledger-form [name=symbol]')).toBeHidden();await expect(page.locator('#ledger-form [name=toAmount]')).toBeHidden();const csv=exportLedgerCSV([{id:'cash1',timestamp:'2026-10-01T10:00:00Z',type:'DEPOSIT',currency:'USD',amount:'1000'}]);await page.locator('#csv-file').setInputFiles({name:'ledger.csv',mimeType:'text/csv',buffer:Buffer.from(csv)});await expect(page.locator('#import-preview')).toContainText('1 nieuwe');expect(store.get().events).toHaveLength(0);await page.locator('#confirm-import').click();await expect(page.locator('#feature-message')).toContainText('Import opgeslagen');await page.locator('#csv-file').setInputFiles({name:'ledger2.csv',mimeType:'text/csv',buffer:Buffer.from(csv)});await expect(page.locator('#import-preview')).toContainText('0 nieuwe');await expect(page.locator('#confirm-import')).toBeDisabled();expect(store.get().events).toHaveLength(1);});
test('watchlist, journal and evaluation survive reload',async({page})=>{const store=await setup(page);await ready(page,root+'radar');await expect(page.locator('#data-status')).toContainText('versie 1');await page.locator('#watch-form input').fill('OPEN');await page.locator('#watch-form button').click();await expect(page.locator('[data-analyze=OPEN]')).toBeVisible();await page.locator('.tabs').getByText('Journal').click();const f=page.locator('#journal-form');for(const [k,v]of Object.entries({symbol:'OPEN',entry:'3',stop:'2.8',target1:'3.5',target2:'4',thesis:'Wacht op bevestiging boven VWAP'}))await f.locator('[name='+k+']').fill(v);await f.getByRole('button').click();await expect(page.locator('.journal-list')).toContainText('Wacht op bevestiging');await page.locator('[data-journal-status]').selectOption('reviewed');await page.locator('[data-evaluation]').fill('Niet gehandeld: volume te laag');await page.getByRole('button',{name:'Evaluatie opslaan'}).click();await page.reload();await expect(page.locator('[data-evaluation]')).toHaveValue('Niet gehandeld: volume te laag');expect(store.get().watchlist).toEqual(['OPEN']);});
test('provider errors show no invented chart and manual scenario includes costs',async({page})=>{await setup(page);await ready(page,root+'analyzer');await page.locator('#market-form [name=symbol]').fill('OPEN');await page.locator('#market-form button').click();await expect(page.locator('#market-result')).toContainText('MARKET_NOT_CONFIGURED');await expect(page.locator('.price-chart')).toHaveCount(0);const f=page.locator('#scenario-form');for(const[k,v]of Object.entries({entry:'10',stop:'9',target1:'12',target2:'14',quantity:'100',fees:'2',slippage:'0.01'}))await f.locator('[name='+k+']').fill(v);await f.getByRole('button').click();await expect(page.locator('#scenario-result')).toContainText('104.00');await expect(page.locator('#scenario-result')).toContainText('196.00');});
test('confirmed authentication failure immediately removes private rendered data',async({page})=>{const store=await setup(page);await ready(page,root+'radar');await expect(page.locator('#data-status')).toContainText('versie 1');await page.locator('#watch-form input').fill('NVDA');await page.locator('#watch-form button').click();await expect(page.locator('[data-analyze=NVDA]')).toBeVisible();store.expire();await page.locator('#state-reload').click();await expect(page.locator('[data-analyze=NVDA]')).toHaveCount(0);await expect(page.locator('#watch-form button')).toBeDisabled();});
test('all direct routes, refresh and mobile forms load without console errors or overflow',async({page})=>{await setup(page);const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width:320,height:800});for(const route of ['portfolio','radar','analyzer','journal','settings']){await ready(page,root+route);await expect(page.locator('h1')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.reload();await expect(page.locator('.splash')).toBeHidden();}expect(errors).toEqual([]);});
test('pending state save cannot restore private values after an authorization failure',async({page})=>{await setup(page);let pending;await page.route('**/api/v1/state',async route=>{if(route.request().method()==='PUT'){pending=route;return;}return route.fulfill({json:{data:initial()}});});await ready(page,root+'radar');await expect(page.locator('#data-status')).toContainText('versie 1');await page.locator('#watch-form input').fill('NVDA');await page.locator('#watch-form button').click();await expect.poll(()=>Boolean(pending)).toBe(true);await page.route('**/api/v1/market/candles?**',route=>route.fulfill({status:401,json:{error:{code:'UNAUTHENTICATED'}}}));await page.locator('#market-form [name=symbol]').fill('OPEN');await page.locator('#market-form button').click();await expect(page.locator('#watch-form button')).toBeDisabled();await pending.fulfill({json:{data:{...initial(),version:2,watchlist:['NVDA']}}});await page.locator('.tabs').getByText('Dashboard').click();await expect(page.locator('main')).not.toContainText('NVDA');});
test('margin authorization failure produces no unhandled errors',async({page})=>{const store=await setup(page);const errors=[];page.on('pageerror',e=>errors.push(e.message));await ready(page,root+'portfolio');await expect(page.locator('#data-status')).toContainText('versie 1');store.expire();await page.locator('#margin-enabled').click();await expect(page.locator('#margin-enabled')).toBeDisabled();expect(errors).toEqual([]);});
test('logout discards pending settings save and clears the form without errors',async({page})=>{await setup(page);let pending;await page.route('**/api/v1/settings',async route=>{if(route.request().method()==='PATCH'){pending=route;return;}return route.fulfill({json:{data:profile}});});const errors=[];page.on('pageerror',e=>errors.push(e.message));await ready(page,root+'settings');await expect(page.locator('#account-status')).toContainText('Ingelogd');await page.locator('#profile-name').fill('Private new name');await page.locator('#account-save').click();await expect.poll(()=>Boolean(pending)).toBe(true);await expect(page.locator('#account-reload')).toBeDisabled();await page.route('**/cdn-cgi/access/logout',route=>route.fulfill({body:'Logged out'}));await page.locator('#account-logout').click();await pending.fulfill({json:{data:{...profile,display_name:'Private new name',version:2}}});await page.goto(root);await expect(page.locator('main')).not.toContainText('Private new name');expect(errors).toEqual([]);});
test('mobile workspace is visible with no CSP violations',async({page},testInfo)=>{await setup(page);const violations=[];page.on('console',m=>{if(m.type()==='error'&&/Content Security|violates|Refused|Unhandled/i.test(m.text()))violations.push(m.text());});await page.setViewportSize({width:390,height:844});await ready(page,root+'portfolio');await expect(page.locator('#data-status')).toContainText('versie 1');expect(violations).toEqual([]);if(testInfo.project.name==='chromium')await page.screenshot({path:'artifacts/portfolio-chromium.png',fullPage:true,caret:'initial'});});
test('one candle renders finite chart and clears completed processing text',async({page})=>{await setup(page);await page.route('**/api/v1/market/candles?**',route=>route.fulfill({json:{data:{symbol:'OPEN',interval:'5min',provider:'Twelve Data',timezone:'UTC',exchange:'NASDAQ',currency:'USD',marketSession:'unverified',realtime:'unverified',delay:'unverified',retrievedAt:new Date().toISOString(),asOf:'2026-10-09T19:55:00Z',stale:true,candles:[{time:'2026-10-09T19:55:00Z',o:2,h:2.3,l:1.9,c:2.23,v:100}]}}}));await ready(page,root+'analyzer');await page.locator('#market-form [name=symbol]').fill('OPEN');await page.locator('#market-form button').click();await expect(page.locator('#market-result')).toContainText('2.23 USD');await expect(page.locator('#feature-message')).toBeEmpty();expect(await page.locator('.price-chart polyline').getAttribute('points')).not.toMatch(/NaN|Infinity/);await expect(page.locator('#market-result')).toContainText('Wachten');});
const closedEvents=()=>[{id:'d',timestamp:'2026-10-01T10:00:00Z',type:'DEPOSIT',currency:'USD',amount:'1000'},{id:'b',timestamp:'2026-10-02T10:00:00Z',type:'BUY',currency:'USD',symbol:'OPEN',quantity:'100',price:'3',fee:'1',feeCurrency:'USD'},{id:'s',timestamp:'2026-10-03T10:00:00Z',type:'SELL',currency:'USD',symbol:'OPEN',quantity:'100',price:'3.5',fee:'1',feeCurrency:'USD'}];
test('delayed canonical CSV cannot cross expired session into freshly loaded account',async({page})=>{
 const store=await setup(page);const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await ready(page,root+'portfolio');await expect(page.locator('#data-status')).toContainText('versie 1');
 const {exportLedgerCSV}=await import('../app/ledger.mjs');
 const csv=exportLedgerCSV([{id:'private-old-owner-deposit',timestamp:'2026-10-01T10:00:00Z',type:'DEPOSIT',currency:'USD',amount:'321'}]);
 await page.evaluate(()=>{const original=File.prototype.text;File.prototype.text=function(){if(this.name!=='old-owner.csv')return original.call(this);window.oldOwnerReadStarted=true;return new Promise(resolve=>{window.releaseOldOwnerCSV=resolve;});};});
 await page.locator('#csv-file').setInputFiles({name:'old-owner.csv',mimeType:'text/csv',buffer:Buffer.from(csv)});
 await expect.poll(()=>page.evaluate(()=>window.oldOwnerReadStarted===true)).toBe(true);
 store.expire();await page.locator('#state-reload').click();await expect(page.locator('#csv-file')).toBeDisabled();
 const next={...initial(),version:7,events:[{id:'new-owner-deposit',timestamp:'2026-10-01T10:00:00Z',type:'DEPOSIT',currency:'USD',amount:'42'}]};
 let writes=0;await page.route('**/api/v1/state',route=>{if(route.request().method()==='PUT')writes++;return route.fulfill({json:{data:next}});});
 await page.locator('#state-reload').click();await expect(page.locator('#data-status')).toContainText('versie 7');await expect(page.locator('.dashboard-kpis .card').nth(0)).toContainText('42');
 await page.evaluate(async text=>{window.releaseOldOwnerCSV(text);await Promise.resolve();await Promise.resolve();},csv);
 await expect(page.locator('#import-preview')).toBeEmpty();await expect(page.locator('#confirm-import')).toHaveCount(0);await expect(page.locator('main')).not.toContainText('321');
 expect(writes).toBe(0);expect(errors).toEqual([]);
});
test('journal linking produces executed results and historical cash excludes later sales',async({page})=>{const store=await setup(page);store.get().events=closedEvents();store.get().journal=[{id:'plan',symbol:'OPEN',createdAt:'2026-10-01T09:00:00Z',thesis:'Test fixture',entry:'3',stop:'2.8',target1:'3.5',target2:'4',status:'reviewed',evaluation:'Closed'}];await ready(page,root+'journal');await page.locator('[data-journal-links=plan]').selectOption(['b','s']);await page.getByRole('button',{name:'Evaluatie opslaan'}).click();await expect(page.getByRole('heading',{name:'Resultaten van gekoppelde transacties'}).locator('..')).toContainText('48');expect(store.get().journal[0].eventIds).toEqual(['b','s']);await page.reload();await expect(page.locator('[data-journal-links=plan] option:checked')).toHaveCount(2);await page.locator('.tabs').getByText('Portfolio').click();await page.locator('#history-form input').fill('2026-10-02T12:00:00Z');await page.locator('#history-form button').click();await expect(page.locator('#history-result')).toContainText('699');await expect(page.locator('#history-result')).toContainText('100');});
test('broker mapping requires explicit mapping and review before persistence',async({page})=>{const store=await setup(page);await ready(page,root+'portfolio');await page.locator('details summary').click();const csv='BrokerID,Datum,Soort,Munt,Bedrag\nrow1,2026-10-01T10:00:00Z,Deposit,USD,1000\n';await page.locator('#mapped-csv-file').setInputFiles({name:'broker.csv',mimeType:'text/csv',buffer:Buffer.from(csv)});for(const [field,header]of Object.entries({id:'BrokerID',timestamp:'Datum',type:'Soort',currency:'Munt',amount:'Bedrag'}))await page.locator('[data-map='+field+']').selectOption(header);await page.locator('[name=buyLabel]').fill('unused');await page.locator('[data-map=type]').selectOption('');await page.locator('[name=fixedType]').selectOption('DEPOSIT');await page.getByRole('button',{name:'Mapping controleren'}).click();await expect(page.locator('#mapping-preview')).toContainText('1/1');expect(store.get().events).toHaveLength(0);await page.getByRole('button',{name:'Gecontroleerde boekingen importeren'}).click();await expect(page.locator('#feature-message')).toContainText('Broker-import opgeslagen');expect(store.get().events).toHaveLength(1);});
test('alert fires once from trusted closed candle and read state persists',async({page})=>{await page.clock.setFixedTime(new Date('2026-10-09T15:06:00Z'));const store=await setup(page);store.get().alerts=[{id:'alert1',symbol:'OPEN',direction:'above',price:'2',enabled:true,triggeredAt:null}];const time='2026-10-09T15:00:00Z';const feed={verified:true,exchange:'NASDAQ',exchangeTimezone:'America/New_York',entitlementVerified:true,entitlementVerifiedAt:'2026-10-09T14:00:00Z',entitlementExpiresAt:'2026-10-10T14:00:00Z',volumeCoverage:'partial',displayRights:'verified',currentMarketStatus:{state:'open',provider:'Twelve Data',exchange:'NASDAQ',basis:'provider_market_state',scope:'current_exchange_status',stale:false,asOf:'2026-10-09T15:06:00Z'},symbol:'OPEN',interval:'5min',provider:'Twelve Data',timezone:'UTC',currency:'USD',marketSession:'regular',realtime:true,delay:0,stale:false,complete:true,asOf:time,candles:[{time,o:2,h:2.4,l:1.9,c:2.3,v:100,complete:true,completedAt:new Date(Date.parse(time)+300000).toISOString()}]};await page.route('**/api/v1/market/candles?**',r=>r.fulfill({json:{data:feed}}));await ready(page,root+'radar');await expect(page.locator('#data-status')).toContainText('versie 1');await page.getByRole('button',{name:'Meldingen controleren',exact:true}).click();await expect.poll(()=>store.get().alerts[0].triggeredAt).not.toBeNull();expect(store.get().alerts[0].enabled).toBe(false);const version=store.get().version;await page.locator('#market-form [name=symbol]').fill('OPEN');await page.locator('#market-form button').click();await expect(page.locator('.price-chart')).toBeVisible();expect(store.get().version).toBe(version);await page.getByRole('button',{name:'Meldingen',exact:true}).click();await expect(page.locator('.overlay')).toContainText('Nieuw');await page.getByRole('button',{name:'Alles als gelezen markeren'}).click();await expect(page.locator('.overlay')).toContainText('Gelezen');expect(store.get().alerts[0].readAt).not.toBeNull();});
test('broader radar compares common historical windows with SPY without inventing live ranking',async({page})=>{await setup(page);await page.route('**/api/v1/market/candles?**',route=>{const u=new URL(route.request().url());const symbol=u.searchParams.get('symbol');const candles=Array.from({length:40},(_,i)=>({time:new Date(Date.UTC(2026,9,8,14)+i*900000).toISOString(),o:10+i*.01,h:10.2+i*.01,l:9.8+i*.01,c:10+i*.01,v:100000,complete:true,completedAt:new Date(Date.UTC(2026,9,8,14)+(i+1)*900000).toISOString()}));return route.fulfill({json:{data:{symbol,interval:'15min',provider:'Twelve Data',timezone:'UTC',exchange:'NASDAQ',currency:'USD',marketSession:'unverified',realtime:'unverified',delay:'unverified',stale:true,asOf:candles.at(-1).time,candles}}});});await ready(page,root+'radar');await page.getByRole('button',{name:'Breder zoeken'}).click();await expect(page.locator('#scan-results')).toContainText('Historische vergelijking');await expect(page.locator('#scan-results')).toContainText('SPY');await expect(page.locator('#scan-results tbody tr')).toHaveCount(7);await expect(page.locator('#scan-results')).toContainText('OPEN');await expect(page.locator('#scan-results')).not.toContainText('Bevestigde rangschikking:');});

test('authoritative market status is visible without promoting unknown data rights',async({page})=>{await setup(page);await page.route('**/api/v1/market/status?exchange=NASDAQ',r=>r.fulfill({json:{data:{exchange:'NASDAQ',provider:'Twelve Data',state:'closed',asOf:'2026-10-10T10:00:00Z',basis:'provider_market_state',scope:'current_exchange_status',stale:false}}}));await ready(page,root+'analyzer');await expect(page.locator('#data-status')).toContainText('versie 1');await page.getByRole('button',{name:'Beursstatus controleren'}).click();await expect(page.locator('#market-status-result')).toContainText('Gesloten');await expect(page.locator('#market-status-result')).toContainText('Weergaverechten en datavertraging worden afzonderlijk gecontroleerd');});

test('USD cash can check FX without positions and unverified rate stays indicative',async({page})=>{const store=await setup(page);store.get().events=[{id:'usd',timestamp:'2026-10-01T10:00:00Z',type:'DEPOSIT',currency:'USD',amount:'100'}];await page.route('**/api/v1/market/fx',r=>r.fulfill({json:{data:{symbol:'USD/EUR',currency:'EUR',baseCurrency:'USD',rate:'0.85',price:'0.85',source:'Twelve Data',provider:'Twelve Data',asOf:new Date().toISOString(),retrievedAt:new Date().toISOString(),timezone:'UTC',delay:'unverified',realtime:'unverified',verified:false,schemaVerified:true,indicative:true,stale:false}}}));await ready(page,root+'portfolio');await expect(page.locator('#data-status')).toContainText('versie 1');await page.getByRole('button',{name:'Koersen en FX controleren'}).click();await expect(page.locator('section').filter({has:page.getByRole('heading',{name:'Waarde en concentratie'})})).toContainText('USD/EUR 0.85');await expect(page.locator('section').filter({has:page.getByRole('heading',{name:'Waarde en concentratie'})})).toContainText('Indicatief; actualiteit en datavertraging niet bevestigd');await expect(page.locator('.indicator-grid p').filter({hasText:'Geconsolideerd EUR actueel'}).locator('strong')).toHaveText('—');expect(store.get().version).toBe(1);});
