import test from 'node:test';
import assert from 'node:assert/strict';
import {classifyCandleSession,completedFeed,compareHistoricalFeeds,entitlementMetadata} from '../app/market-quality.mjs';
import {analyzeCandles,compareHistoricalOpportunities,rankOpportunities} from '../app/analysis.mjs';
function feed(symbol='OPEN',interval='5min') {
 const end=Date.parse('2026-10-09T19:55:00Z');
 const candles=Array.from({length:40},(_,i)=>{const c=100+Math.sin(i*.9)*.4+i*.025;return {time:new Date(end-(39-i)*parseInt(interval)*60000).toISOString(),o:c,h:c+.2,l:c-.3,c,v:10000};});candles[22].h=104;
 return {symbol,interval,exchange:'NASDAQ',exchangeTimezone:'America/New_York',currency:'USD',provider:'Twelve Data',timezone:'UTC',candles,asOf:candles.at(-1).time,stale:true,realtime:'unverified',delay:'unverified',displayRights:'unverified'};
}
const now=Date.parse('2026-10-10T12:00:00Z');
test('historical candle session classified with DST and explicit calendar uncertainty',()=>{for(const [time,session] of [['2026-10-09T13:30:00Z','regular'],['2026-01-09T14:30:00Z','regular'],['2026-10-09T12:00:00Z','premarket'],['2026-10-09T20:00:00Z','after-hours'],['2026-10-10T15:00:00Z','closed']]){const value=classifyCandleSession(time,{exchange:'NASDAQ'});assert.equal(value.session,session);assert.equal(value.calendarVerified,false);assert.equal(value.basis,'exchange_local_clock');}assert.equal(classifyCandleSession('2026-10-09T15:00:00Z',{exchange:'London'}).session,'unverified');});
test('drop forming bars before calculating indicators',()=>{const f=feed();f.stale=false;f.candles.at(-1).c=500;f.candles.at(-1).h=501;const end=Date.parse(f.asOf);const done=completedFeed(f,end+60000);assert.equal(done.droppedFormingBars,1);const a=analyzeCandles(f,{now:end+60000});assert.equal(a.indicators.close,f.candles.at(-2).c);assert.equal(a.asOf,f.candles.at(-2).time);assert.equal(a.sourceAsOf,f.asOf);});
test('stale unknown-delay feeds retain historical metrics and hypothetical plan without ranking',()=>{const f=feed(),a=analyzeCandles(f,{now});assert.equal(a.status,'wait');assert.equal(a.scenario,null);assert.equal(a.score,null);assert.ok(a.hypotheticalScenario);assert.equal(a.hypotheticalScenario.actionable,false);assert.ok(a.volatility.atr>0);assert.ok(a.volatility.barReturnRootMeanSquare>=0);assert.equal(a.lastCandleSession.session,'regular');assert.equal(a.currentMarketStatus.state,'unverified');assert.deepEqual(rankOpportunities([f],{now}),[]);});
test('comparison aligns identical historical timestamps irrespective freshness',()=>{const f=feed(),b=feed('SPY');b.candles=b.candles.map((c,i)=>({...c,o:200+i*.01,h:201+i*.01,l:199+i*.01,c:200+i*.01}));const a=compareHistoricalFeeds(f,b,{now});assert.equal(a.comparable,true);assert.equal(a.actionable,false);assert.equal(a.stale,true);assert.ok(Number.isFinite(a.relativeStrength));assert.equal(a.asOf,f.asOf);assert.equal(analyzeCandles(f,{benchmark:b,now}).relativeStrength,a.relativeStrength);assert.equal(compareHistoricalOpportunities([f],{benchmark:b,now})[0].comparisonBasis,'historical_descriptive');});
test('misaligned currency interval gap and corrupt benchmark fail comparison',()=>{const f=feed(),b=feed('SPY');for(const mutate of [x=>x.currency='EUR',x=>x.interval='15min',x=>x.candles.splice(-3,1),x=>x.candles.at(-2).c=NaN]){const altered=structuredClone(b);mutate(altered);assert.equal(compareHistoricalFeeds(f,altered,{now}).comparable,false);}});
test('generic docs and expired profile never imply verified entitlement or display rights',()=>{const unknown=entitlementMetadata(undefined,now);assert.equal(unknown.realtime,'unverified');assert.equal(unknown.displayRights,'unverified');assert.equal(unknown.documentedDefaultFeed.availability,'realtime_us_equities');const profile={provider:'Twelve Data',scope:'US_EQUITIES',evidence:'owner_account_verified',verifiedAt:'2026-10-09T00:00:00Z',expiresAt:'2026-10-15T00:00:00Z',realtime:true,delayMinutes:0,volumeCoverage:'partial',displayRights:'unverified'};assert.equal(entitlementMetadata(JSON.stringify(profile),now).displayRights,'unverified');assert.equal(entitlementMetadata({...profile,expiresAt:'2026-10-09T00:00:00Z'},now).entitlementVerified,false);assert.equal(entitlementMetadata({...profile,realtime:true,delayMinutes:15},now).entitlementVerified,false);});
