const {test,expect}=require('@playwright/test');
const root='http://127.0.0.1:8765/app/';
const profile={display_name:'Portfolio fixture',locale:'nl-NL',timezone:'Europe/Amsterdam',display_currency:'EUR',risk_budget_eur:'100',version:1,preferences:{showUSD:true,defaultInterval:'15min',inAppAlerts:true,maxPositionPercent:'25.00',hideAmounts:false}};
const events=[{id:'d',type:'DEPOSIT',timestamp:'2026-10-01T13:00:00Z',currency:'USD',amount:'1000'},{id:'b',type:'BUY',timestamp:'2026-10-01T14:00:00Z',currency:'USD',symbol:'OPEN',quantity:'2',price:'3'},{id:'s',type:'SELL',timestamp:'2026-10-02T14:00:00Z',currency:'USD',symbol:'OPEN',quantity:'1',price:'4'}];
const plan={id:'p',symbol:'OPEN',createdAt:'2026-10-01T12:00:00Z',entry:'3',stop:'2',target1:'4',target2:'5',thesis:'Source checked original thesis',status:'planned',evaluation:''};
async function setup(page,{locale='nl-NL',journal=[plan],preferences={}}={}){let stored={version:1,events:structuredClone(events),journal:structuredClone(journal),watchlist:[],alerts:[],preferences:{allowMargin:false,costMethod:'average'}};await page.route('**/api/v1/**',route=>{const req=route.request(),path=new URL(req.url()).pathname;if(path.endsWith('/settings'))return route.fulfill({json:{data:{...profile,locale,preferences:{...profile.preferences,...preferences}}}});if(path.endsWith('/session'))return route.fulfill({json:{data:{authenticated:true,settings:{...profile,locale,preferences:{...profile.preferences,...preferences}}}}});if(path.endsWith('/state')){if(req.method()==='PUT')stored={...req.postDataJSON(),version:stored.version+1};return route.fulfill({json:{data:stored}})}return route.fulfill({status:503,json:{error:{code:'MARKET_NOT_CONFIGURED'}}});});return()=>stored;}
async function ready(page,route){await page.goto(root+route);await expect(page.locator('.splash')).toBeHidden();await expect(page.locator('#data-status')).toBeVisible();}
test('portfolio filters, position detail and exact realized chart work at 375px',async({page})=>{await setup(page);await page.setViewportSize({width:375,height:812});await ready(page,'portfolio');await expect(page.locator('.performance-chart')).toBeVisible();await expect(page.locator('.performance-history')).toContainText('geen totaalrendement');await page.locator('#ledger-type').selectOption('SELL');await expect(page.locator('#ledger-filter-results tbody tr')).toHaveCount(1);await page.locator('#ledger-search').fill('AAPL');await expect(page.locator('#ledger-filter-results')).toContainText('Geen boekingen');await page.locator('#ledger-filter-reset').click();await expect(page.locator('#ledger-filter-results tbody tr')).toHaveCount(3);await page.locator('#portfolio-position').selectOption('OPEN');await expect(page.locator('#portfolio-position-detail')).toContainText('Gemiddelde kostprijs: 3');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});
test('live ledger preview rejects oversell without persistence',async({page})=>{const state=await setup(page);await ready(page,'portfolio');const form=page.locator('#ledger-form');await form.locator('[name=type]').selectOption('SELL');await form.locator('[name=symbol]').fill('OPEN');await form.locator('[name=quantity]').fill('2');await form.locator('[name=price]').fill('4');await expect(form.locator('button.primary')).toBeDisabled();await expect(page.locator('#ledger-live-preview')).toContainText('OVERSELL');expect(state().events).toHaveLength(3);await form.locator('[name=quantity]').fill('1');await expect(form.locator('button.primary')).toBeEnabled();await expect(page.locator('#ledger-live-preview')).toContainText('nog niet opgeslagen');});
test('journal edits an unexecuted original plan, uploads bounded screenshot and filters',async({page})=>{const state=await setup(page);await ready(page,'journal');await page.locator('[data-journal-record=p] summary').click();const form=page.locator('[data-plan-edit=p]');await form.locator('[name=initialRisk]').fill('2');await form.locator('[name=initialQuantity]').fill('2');await form.locator('[name=dataChecked]').check();await form.locator('button').click();await expect(page.locator('#feature-message')).toContainText('bijgewerkt');expect(state().journal[0].initialRisk).toBe('2');expect(state().journal[0].checklist.dataChecked).toBe(true);await page.locator('[data-plan-image=p]').setInputFiles({name:'source.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64')});await expect(page.locator('.journal-attachment img')).toBeVisible();expect(state().journal[0].attachments[0].kind).toBe('image');await page.locator('#journal-search').fill('AAPL');await expect(page.locator('[data-journal-record=p]')).toBeHidden();await page.locator('#journal-filter-reset').click();await expect(page.locator('[data-journal-record=p]')).toBeVisible();});
test('executed journal locks original plan and English portfolio copy is actual translated UI',async({page})=>{await setup(page,{locale:'en-US',journal:[{...plan,status:'executed',eventIds:['b']}]});await ready(page,'journal');await expect(page.locator('[data-plan-edit]')).toHaveCount(0);await expect(page.locator('.journal-plan-detail')).toContainText('locked after execution');await page.goto(root+'portfolio');await expect(page.locator('.splash')).toBeHidden();await expect(page.getByRole('heading',{name:'Your portfolio',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Booking history',exact:true})).toBeVisible();await expect(page.locator('.performance-history')).toContainText('not total return');});

test('display preference hides optional USD consolidated side value while native ledger remains explicit',async({page})=>{await setup(page,{preferences:{showUSD:false}});await ready(page,'portfolio');await expect(page.locator('[data-usd-side-value]')).toHaveCount(0);await expect(page.getByRole('heading',{name:'USD cash',exact:true})).toBeVisible();await expect(page.locator('#ledger-filter-results')).toContainText('USD');});
test('hidden amounts suppress private Portfolio and Journal financial forms',async({page})=>{await setup(page,{preferences:{hideAmounts:true}});await ready(page,'portfolio');await expect(page.getByText('Bedragen zijn verborgen.',{exact:false})).toBeVisible();await expect(page.locator('#ledger-form')).toHaveCount(0);await expect(page.locator('.performance-chart')).toHaveCount(0);await page.goto(root+'journal');await expect(page.locator('.splash')).toBeHidden();await expect(page.locator('#journal-form')).toHaveCount(0);await expect(page.locator('[data-open-analyzer=OPEN]')).toBeVisible();});

test('position search sort reset and contextual alert action preserve actual symbol',async({page})=>{await setup(page);await ready(page,'portfolio');await page.locator('#position-search').fill('AAPL');await expect(page.locator('[data-position-row=OPEN]')).toBeHidden();await expect(page.locator('#position-filter-count')).toContainText('Geen boekingen');await page.locator('#position-reset').click();await page.locator('#position-sort').selectOption('costBasis');await expect(page.locator('[data-position-row=OPEN]')).toBeVisible();await page.locator('[data-position-row=OPEN] a').click();await expect(page).toHaveURL(/\/alerts\?symbol=OPEN&alert=1/);await expect(page.locator('#alert-form [name=symbol]')).toHaveValue('OPEN');});
test('journal CSV export is formula-safe and actual executed plan deletion is disabled',async({page})=>{await setup(page,{journal:[{...plan,status:'executed',eventIds:['b'],thesis:'=SUM(1,2)'}]});await ready(page,'journal');await expect(page.locator('[data-journal-delete=p]')).toBeDisabled();await expect(page.locator('[data-journal-record=p]')).toContainText('kunnen niet worden verwijderd');const downloadPromise=page.waitForEvent('download');await page.locator('#journal-csv-export').click();const download=await downloadPromise;expect(download.suggestedFilename()).toBe('tradepilot-journal.csv');const text=require('node:fs').readFileSync(await download.path(),'utf8');expect(text).toContain(`"'=SUM(1,2)"`);});
