import {pt} from './portfolio-copy.mjs';
import {jt} from './journal-panels.mjs';
import {calculatePortfolio,projectLedger,quoteFromCandles} from './portfolio.mjs';
import {journalStatistics} from './journal.mjs';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const table=(heads,rows)=>`<div class="table-scroll" tabindex="0" aria-label="Tabel, horizontaal verschuifbaar"><table><thead><tr>${heads.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${heads.length}">Nog geen gegevens.</td></tr>`}</tbody></table></div>`;
const amount=x=>x===null||x===undefined?'—':esc(x);
const labels={current:'Actueel',historical:'Historisch',stale:'Verouderd',unverified:'Indicatief · niet geverifieerd',missing:'Koers ontbreekt',closed:'Gesloten positie'};
export function valuationPanel(state,feeds,fx=null,preferences={}){
 if(!state)return '';
 const quotes=Object.fromEntries([...feeds].map(([symbol,feed])=>[symbol,quoteFromCandles(feed)]));
 const p=calculatePortfolio(state.events,{quotes,fx,...state.preferences});
 const displayCurrency=preferences.displayCurrency==='USD'?'USD':'EUR';
 const displayValue=displayCurrency==='USD'?p.currentUSDValue:p.currentEURValue;
 return `<section class="card dashboard-section"><div class="section-top"><h2>Waarde en concentratie</h2><button class="secondary" id="refresh-valuation" >Koersen en FX controleren</button></div><p class="data-label">${pt('coverage',{covered:p.concentration.coveredPositions,open:p.concentration.openPositions})}</p>${table(['Ticker','Koers','Waarde','Ongerealiseerd resultaat','Aandeel gedekte posities','Bron en tijd'],p.positions.filter(x=>Number(x.quantity)>0).map(x=>`<tr><td><button type="button" class="ticker-link" data-open-analyzer="${esc(x.symbol)}" aria-label="Analyseer ${esc(x.symbol)}">${esc(x.symbol)}</button></td><td>${amount(x.quote.price)} ${esc(x.currency)}</td><td>${amount(x.marketValue)}</td><td>${amount(x.unrealized)}</td><td>${amount(x.coveredWeightPercent)}${x.coveredWeightPercent===null?'':'%'}</td><td>${esc(labels[x.quote.status])}<br>${esc(x.quote.source||'—')} · ${esc(x.quote.asOf||'—')}</td></tr>`))}<div class="indicator-grid">${['USD','EUR'].map(c=>`<p>${pt('nativeNet',{currency:c})}<strong>${amount(p.totals[c].netAssetValue)}</strong></p>`).join('')}<p>${displayCurrency==='USD'?'Consolidated current USD':'Geconsolideerd EUR actueel'}<strong>${amount(displayValue)}</strong></p>${displayCurrency==='EUR'&&preferences.showUSD!==false?`<p data-usd-side-value>USD<strong>${amount(p.currentUSDValue)}</strong></p>`:''}<p>EUR-schatting uit beschikbare koersen<strong>${amount(p.indicativeUnverifiedEURValue)}</strong></p></div><p class="data-label">Concentratie: alleen gedekte aandelen binnen dezelfde valuta; geen cash of margin in de weging. Ontbrekende of niet-actuele koersen verhinderen actuele totalen. Zonder gecontroleerde USD/EUR-koers blijft EUR-consolidatie onbekend.</p>${fx?`<p class="data-label">USD/EUR ${esc(fx.rate)} · Bron ${esc(fx.provider)} · UTC ${esc(fx.asOf)} · ${fx.verified===true?'Gecontroleerd':'Indicatief; actualiteit en datavertraging niet bevestigd'}</p>`:''}<div id="valuation-status" role="status"></div></section>`;
}
export function historyPanel(state){if(!state)return '';return `<section class="card dashboard-section"><h2>Historische administratie</h2><form id="history-form" class="toolbar"><label>Peildatum en tijd (UTC)<input name="asOf" required value="${new Date().toISOString()}" aria-label="Peildatum en tijd (UTC)"></label><button class="secondary">Historie berekenen</button></form><div id="history-result" role="status"></div><p class="data-label">Reconstructie uit bevestigde boekingen tot het gekozen tijdstip; geen actuele koersen terugplaatsen in historische resultaten.</p></section>`;}
export function historyResult(state,asOf){const l=projectLedger(state.events,{asOf,...state.preferences});return `<p>${esc(l.asOf)} · ${l.eventCount} boekingen · cash USD ${esc(l.cash.USD)} / EUR ${esc(l.cash.EUR)} · gerealiseerd USD ${esc(l.realized.USD)} / EUR ${esc(l.realized.EUR)}</p>${table(['Ticker','Aantal','Kostbasis','Valuta'],l.positions.filter(p=>Number(p.quantity)>0).map(p=>`<tr><td>${esc(p.symbol)}</td><td>${esc(p.quantity)}</td><td>${esc(p.costBasis)}</td><td>${esc(p.currency)}</td></tr>`))}`;}
export function statisticsPanel(state){if(!state)return '';const s=journalStatistics(state.journal,state.events,state.preferences);return `<section class="card dashboard-section"><h2>Resultaten van gekoppelde transacties</h2><div class="indicator-grid"><p>Afgesloten trades<strong>${s.closedCount}</strong></p><p>Winst / verlies / gelijk<strong>${s.wins} / ${s.losses} / ${s.breakeven}</strong></p><p>Winpercentage<strong>${s.winRate===null?'—':(100*s.winRate).toFixed(1)+'%'}</strong></p><p>Netto USD<strong>${esc(s.netByCurrency.USD)}</strong></p><p>Netto EUR<strong>${esc(s.netByCurrency.EUR)}</strong></p></div><div class="indicator-grid"><p>${pt('duration')}<strong>${s.averageDurationHours===null?'—':s.averageDurationHours.toFixed(2)}</strong></p><p>${jt('riskR')}<strong>${esc(s.averageR??'—')}</strong></p><p>${jt('riskSample')}<strong>${s.rSampleCount}</strong></p>${['USD','EUR'].map(c=>`<p>${pt('expectancy')} ${c}<strong>${esc(s.metrics[c].expectancy??'—')}</strong></p><p>${pt('profitFactor')} ${c}<strong>${esc(s.metrics[c].profitFactor??'—')} · n=${s.metrics[c].sampleCount}</strong></p>`).join('')}</div><p class="data-label">${pt('statisticsNote',{mixed:s.mixedCurrencyCount,excluded:s.excludedCount})}</p></section>`;}
export function journalLinks(state,row){const used=new Set(state.journal.filter(x=>x.id!==row.id).flatMap(x=>x.eventIds||[]));return `<label>Uitgevoerde boekingen koppelen<select multiple size="4" data-journal-links="${esc(row.id)}" aria-label="Uitgevoerde boekingen koppelen voor ${esc(row.symbol)}">${state.events.filter(e=>['BUY','SELL'].includes(e.type)&&e.symbol===row.symbol).map(e=>`<option value="${esc(e.id)}" ${(row.eventIds||[]).includes(e.id)?'selected':''} ${used.has(e.id)?'disabled':''}>${esc(e.timestamp)} · ${e.type==='BUY'?'Koop':'Verkoop'} ${esc(e.quantity)} @ ${esc(e.price)} ${esc(e.currency)}</option>`).join('')}</select></label><p class="data-label">Selecteer de koop- én verkoopboekingen van deze trade. Een boeking hoort bij maximaal één plan.</p>`;}
export function scenarioPanel(analysis){
 const s=analysis.scenario;const hypothetical=analysis.hypotheticalScenario;
 const l=s||hypothetical||analysis.indicativeLevels;
 if(!l)return '';
 return `<section class="scenario-summary"><h3>${s?'Onderbouwd scenario':hypothetical?'Voorwaardelijk historisch scenario · wachten':'Technische referentieniveaus · wachten'}</h3><div class="indicator-grid">${[['Instap',l.entryZone?l.entryZone.map(v=>Number(v).toFixed(3)).join(' – '):l.entry],['Stop',l.stop],['Doel 1',l.target1],['Doel 2',l.target2],['R/R doel 1',l.rr1],['R/R doel 2',l.rr2]].map(([k,v])=>`<p>${k}<strong>${typeof v==='number'?v.toFixed(3):amount(v)}</strong></p>`).join('')}</div><p class="data-label">${s?'Horizon 1–5 handelsdagen. Ongeldig bij slot onder de stop, verlies van sessie-VWAP of verouderde data.':'Referentieniveaus uit candlehistorie, geen instapadvies of actuele koopkans. Ongeldige volgorde of onvoldoende koersruimte levert geen handelsscenario.'} Kosten/slippage horen bij de persoonlijke scenarioberekening.</p></section>`;
}
export function mappingPanel(){return `<details class="card dashboard-section"><summary>Eigen broker-CSV met kolommapping importeren</summary><p class="data-label">Koppel kolommen expliciet en controleer elke rij. Tickers en USD-cash worden niet uit ISIN of EUR-bedragen geraden. Dit is geen automatische DEGIRO-koppeling.</p><label class="file-label">Broker-CSV kiezen<input type="file" id="mapped-csv-file" accept=".csv,text/csv"></label><div id="mapping-controls"></div><div id="mapping-preview" role="status"></div></details>`;}
