const pages=[['dashboard','Dashboard','⌂'],['portfolio','Portfolio','▤'],['radar','Kansen','◈'],['analyzer','Analyzer','⌁'],['journal','Journal','▣']];
const app=document.getElementById('app');
let searchOpen=false,notificationOpen=false,searchCategory='Aandelen',lastFocus=null;
const route=()=>location.pathname.replace(/\/$/,'').split('/').pop()||'dashboard';
const pageText={
 dashboard:['Jouw tradingoverzicht','Hier komen je portefeuille, marktstatus en maximaal drie onderbouwde kansen samen.'],
 portfolio:['Jouw portefeuille','Transacties, beschikbare cash, posities en EUR/USD-berekeningen worden hier gekoppeld.'],
 radar:['Kansenradar','De scan voor Amerikaanse aandelen wordt pas geactiveerd wanneer marktdata en kwaliteitscontroles werken.'],
 analyzer:['Trade Analyzer','Hier vergelijk je instap, stop-loss, koersdoelen, risico en kosten met je bestaande posities.'],
 journal:['Trade Journal','Leg je handelsplannen, uitvoeringen en evaluaties vast.']
};
function iconButton(label,symbol,id){return '<button type="button" class="icon-button" aria-label="'+label+'" id="'+id+'">'+symbol+'</button>'}
function tabs(cls){return '<nav class="'+cls+'" aria-label="Hoofdnavigatie">'+pages.map(([id,label,symbol])=>'<a class="tab" href="./'+id+'" data-route="'+id+'" '+(route()===id?'aria-current="page"':'')+'><span aria-hidden="true">'+symbol+'</span>'+label+'</a>').join('')+'</nav>'}
function greeting(){const h=new Date().getHours();return h<12?'Goedemorgen':h<18?'Goedemiddag':'Goedenavond'}
function pageContent(id){if(id==='settings')return '<button class="back" data-back>← Terug</button><p class="eyebrow">Voorkeuren</p><h1>Instellingen</h1><p class="muted">De instellingenstructuur is beschikbaar. Opslaan volgt zodra de accountlaag is aangesloten.</p>'+[['Profiel en regio','Naam, taal en tijdzone'],['Valuta en portefeuille','EUR-weergave en USD-transacties'],['Risico en analyse','Risicobudget en analysevoorkeuren'],['Meldingen','Koers- en planmeldingen'],['Data en transparantie','Databronnen, vertraging en marktstatus'],['Privacy en account','Toegang en gegevensbeheer']].map(([title,desc])=>'<div class="settings-row"><strong>'+title+'</strong><span>'+desc+'</span></div>').join('');
 const [title,desc]=pageText[id]||pageText.dashboard;
 return '<p class="eyebrow">TradePilot Pro</p><h1>'+(id==='dashboard'?greeting()+', Alexander':title)+'</h1><p class="muted">'+desc+'</p>'+(id==='dashboard'?'<div class="grid"><section class="card"><h2>Portefeuillewaarde</h2><strong>—</strong><p class="muted">Nog geen gekoppelde portefeuilledata</p></section><section class="card"><h2>Marktstatus</h2><strong>Niet verbonden</strong><p class="muted">Geen geverifieerde actuele koersen</p></section><section class="card"><h2>Kansen</h2><strong>—</strong><p class="muted">Scanner nog niet aangesloten</p></section></div>':'<div class="card" style="margin-top:24px"><h2>Functie in ontwikkeling</h2><p class="muted">De route werkt. De inhoud wordt in een volgende bouwfase aangesloten en getest.</p></div>')+'<div class="notice">Ontwikkelversie · Geen live marktdata, brokerkoppeling of handelsadvies.</div>'}
function render(){const id=route();document.title=(id==='settings'?'Instellingen':(pages.find(p=>p[0]===id)||pages[0])[1])+' · TradePilot Pro';
 app.innerHTML='<div class="shell"><header class="header"><a class="brand" href="./dashboard" data-route="dashboard"><span class="brand-mark" aria-hidden="true">↗</span>TradePilot <span style="color:#2388b9">Pro</span></a><div class="header-actions">'+iconButton('Zoeken','⌕','search')+iconButton('Meldingen','♧','notifications')+iconButton('Instellingen','⚙','settings')+'</div></header>'+tabs('tabs')+'<main class="content" id="main">'+pageContent(id)+'</main></div>'+tabs('bottom');
 if(searchOpen)renderSearch();if(notificationOpen)renderNotifications();
 document.getElementById('search').onclick=()=>{lastFocus=document.activeElement;searchOpen=true;notificationOpen=false;render();document.getElementById('search-input').focus()};
 document.getElementById('notifications').onclick=()=>{lastFocus=document.activeElement;notificationOpen=true;searchOpen=false;render();document.getElementById('close-notifications').focus()};
 document.getElementById('settings').onclick=()=>navigate('settings');
 document.querySelectorAll('[data-route]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();navigate(el.dataset.route)}));
 const back=document.querySelector('[data-back]');if(back)back.onclick=()=>history.length>1?history.back():navigate('dashboard');
}
function navigate(id){searchOpen=false;notificationOpen=false;history.pushState({},'',new URL('./'+id,location.href).pathname);render()}
function closeOverlay(){searchOpen=false;notificationOpen=false;render();if(lastFocus?.id){document.getElementById(lastFocus.id)?.focus()}}
function renderSearch(){const layer=document.createElement('div');layer.className='overlay';layer.setAttribute('role','dialog');layer.setAttribute('aria-modal','true');layer.setAttribute('aria-label','Zoeken');layer.innerHTML='<div class="overlay-inner"><div class="overlay-top"><h1>Zoeken</h1><button class="primary" id="close-search">Sluiten</button></div><label class="sr-only" for="search-input">Zoek ticker of bedrijf</label><input class="search-input" id="search-input" placeholder="Zoek ticker of bedrijf" autocomplete="off"><div class="categories">'+['Aandelen','Mijn portefeuille','Handelsplannen','Journal'].map(x=>'<button class="chip" aria-pressed="'+(x===searchCategory)+'" data-category="'+x+'">'+x+'</button>').join('')+'</div><p class="notice" id="search-status">Zoekgegevens zijn nog niet aangesloten. Er worden geen fictieve resultaten getoond.</p></div>';app.appendChild(layer);layer.querySelector('#close-search').onclick=closeOverlay;layer.querySelectorAll('[data-category]').forEach(el=>el.onclick=()=>{searchCategory=el.dataset.category;layer.querySelectorAll('[data-category]').forEach(x=>x.setAttribute('aria-pressed',String(x===el)))});layer.querySelector('#search-input').addEventListener('input',e=>{layer.querySelector('#search-status').textContent=e.target.value.trim()?'Zoekservice nog niet verbonden. Geen resultaten beschikbaar.':'Zoekgegevens zijn nog niet aangesloten. Er worden geen fictieve resultaten getoond.'})}
function renderNotifications(){const layer=document.createElement('div');layer.className='overlay';layer.setAttribute('role','dialog');layer.setAttribute('aria-modal','true');layer.setAttribute('aria-label','Meldingen');layer.innerHTML='<div class="overlay-inner"><div class="overlay-top"><h1>Meldingen</h1><button class="primary" id="close-notifications">Sluiten</button></div><p class="notice">Er is nog geen meldingenservice aangesloten.</p></div>';app.appendChild(layer);layer.querySelector('button').onclick=closeOverlay}
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&(searchOpen||notificationOpen))closeOverlay();if(e.key==='Tab'&&(searchOpen||notificationOpen)){const layer=document.querySelector('.overlay');const focusables=[...layer.querySelectorAll('button,input')];const first=focusables[0],last=focusables.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
window.addEventListener('popstate',()=>{searchOpen=false;notificationOpen=false;render()});
render();