import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const root=path.resolve(import.meta.dirname,'..');
const assets={};
function walk(dir){for(const item of fs.readdirSync(dir,{withFileTypes:true})){const name=path.join(dir,item.name);if(item.isDirectory())walk(name);else if(/\.(html|js|mjs|css|svg)$/.test(name)&&!item.name.includes('config'))assets['/'+path.relative(root,name).split(path.sep).join('/')]=fs.readFileSync(name,'utf8');}}
walk(path.join(root,'app'));
const revision=crypto.createHash('sha256').update(JSON.stringify(assets)).digest('hex');
const output='// Generated by scripts/build-assets.mjs; do not hand edit.\nexport const assetRevision='+JSON.stringify(revision)+';\nexport const siteAssets='+JSON.stringify(assets)+';\n';
const target=path.join(root,'worker/src/site-assets.mjs');
if(process.argv.includes('--check')){if(fs.readFileSync(target,'utf8')!==output)throw Error('Worker assets differ from frontend; run npm run build');}
else fs.writeFileSync(target,output);
console.log('App asset revision: '+revision);
